version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
  - dependency-name: "@docusaurus/preset-classic"
    versions:
    - 2.0.0-alpha.70
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
  - dependency-name: "@docusaurus/core"
    versions:
    - 2.0.0-alpha.70
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
  - dependency-name: "@docusaurus/theme-live-codeblock"
    versions:
    - 2.0.0-alpha.70
    - 2.0.0-alpha.71
    - 2.0.0-alpha.72
  - dependency-name: intro.js
    versions:
    - 3.2.1
    - 3.3.1
    - 3.4.0
